# Utility targets
.PHONY: clean veryclean

clean:
	$(MAKE) -C examples clean
	$(MAKE) -C fortran clean
	$(MAKE) -C CC clean
	$(MAKE) -C CC_ini clean
	$(MAKE) -C MR clean

veryclean: clean
	$(MAKE) -C examples veryclean
	$(MAKE) -C fortran veryclean
	$(MAKE) -C CC veryclean
	$(MAKE) -C CC_ini veryclean
	$(MAKE) -C MR veryclean
